### ISSUE TITLE
Commander pro / Node pro leds not turning off

### ISSUE THREAD

**Issue by Edaurd** [teug91/IdleRGB2#2]
i have RGB fans and RGB strips and those dont seem to affected by this.
they do support the SDK because games like MK11 work with those and other tools for customizing leds on your peripherals (universal tool for different brands) also works

also would be awesome to make it so we can disable the caps lock thing

**Comment by teug91** [comment]
This app uses [CUE.NET](https://github.com/DarthAffe/CUE.NET) to talk to the devices. Unfortunately, CUE.NET is not being updated to work with new devices.

I don't use Windows anymore, so I no longer have any use for this app. I would consider updating to support more devices and adding a caps lock option if CUE.NET is updated. Switching to [RGB.NET](https://github.com/DarthAffe/RGB.NET) would take more time than I'm comfortable spending on this project.
